version: '3'

services:
  php:
    container_name: beststocks_php
    restart: always
    image: sadykh/php:7.2
    volumes:
      - ./src:/var/www/html:rw
      - ./db:/var/lib/mysql
      - ./logs/supervisor:/var/log/supervisor
  nginx:
    container_name: beststocks_nginx
    restart: always
    image: nginx:latest
    volumes:
      - ./src:/var/www/html:rw
      - ./nginx/conf.d:/etc/nginx/conf.d/:rw
      - ./nginx/logs:/var/log/nginx/:rw
    ports:
      - 85:80
  mariadb:
    container_name: beststocks_db
    image: sadykh/mariadb-utf8:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql:rw
